packages:
  - 'apps/*'
  - 'libs/*'

ignoredBuiltDependencies:
  - '@biomejs/biome'
  - '@parcel/watcher'
  - lmdb
  - msgpackr-extract
  - protobufjs
  - re2
  - unrs-resolver

onlyBuiltDependencies:
  - cypress
  - esbuild
  - nx
