packages:
  - apps/*
  - libs/*

ignoredBuiltDependencies:
  - '@biomejs/biome'
  - '@parcel/watcher'
  - lmdb
  - msgpackr-extract
  - protobufjs
  - re2
  - unrs-resolver
  - esbuild

onlyBuiltDependencies:
  - '@compodoc/compodoc'
  - '@swc/core'
  - cypress
  - nx
