packages:
  - apps/*
  - libs/*

autoInstallPeers: false

allowBuilds:
  '@compodoc/compodoc': false
  '@parcel/watcher': false
  '@swc/core': false
  esbuild: true
  less: false
  lmdb: false
  msgpackr-extract: false
  nx: true
  protobufjs: false
  re2: false
  unrs-resolver: false

minimumReleaseAge: 1440
minimumReleaseAgeStrict: true
